version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 19006:19006
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
