version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 19006:19006
    volumes:
      - ./frontend/src/:/usr/src/app/src
  server:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend/sqlite_data/dev.sqlite:/usr/src/app/database.sqlite
      - ./backend/src/:/usr/src/app/src
