version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend/sqlite_data/dev.sqlite:/usr/src/app/database.sqlite
      - ./backend/src/:/usr/src/app/src
